<a href="https://colab.research.google.com/github/AnuragJaybhaye/HR-Analytics-Dashboard/blob/main/Multi_label_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Dataset

# (Sentence,review_tagging) - (The product was really bad,Not Satisfied)
# Assume that the review_tagging can be of 20 types -> really good, aggressive, Comparative,
# You can also go to multi-label classification. Not sure if the data is there or not ?


# Sentence -> Convert to Embeddings -> Use these embeddings to train a neural Network
# Type of Neural Network -> FCNN (Fully connected neural network), Transformers (Also a type of neural network), Tree algorithm
# I can use transformer for classification, i can FCNN for classification or a simple Tree algorithm for classification


# Part of NLP is word embeddings

In [ ]:
# Plan is simple


# 1. Load the goEmotion dataset -> Load it from hugging face datasets
# 2. Convert each sentence to word embeddings. use that word embedding on which my encoder is trained on
# 3. Use a good encoder like BERT to encode each sentence to sentence embeddings
# 4. Train a neural network

In [ ]:
# Prepare the data -> stored in dataset["train"]
# Convert to word embeddings  (that is used in BERT)
# Use these word embeddings to create sentence embeddings using BERT. Save these sentence embeddings as tensor along with the labels

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

In [ ]:
# 1. Setup
DEVICE = "cuda"
BATCH_SIZE = 50
sbert = SentenceTransformer('all-mpnet-base-v2')
NUM_LABELS = 28

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
dataset = load_dataset("go_emotions", "simplified")
train_data = dataset["train"]
texts = train_data["text"]

README.md: 0.00B [00:00, ?B/s]

simplified/train-00000-of-00001.parquet:   0%|          | 0.00/2.77M [00:00<?, ?B/s]

simplified/validation-00000-of-00001.par(…):   0%|          | 0.00/350k [00:00<?, ?B/s]

simplified/test-00000-of-00001.parquet:   0%|          | 0.00/347k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

In [ ]:
texts[4]

'Dirty Southern Wankers'

In [ ]:
e1 = sbert.encode("sun rises in the east", convert_to_tensor=True)
e2 = sbert.encode("i am very sad today", convert_to_tensor=True)

In [ ]:
e1


tensor([ 4.5624e-03,  1.7585e-02,  4.0083e-03, -1.1922e-02, -2.9092e-02,
        -4.3465e-03, -5.9772e-02, -5.5556e-02, -3.2468e-02, -1.3493e-02,
         1.4089e-02,  7.0518e-02,  1.8477e-02, -7.5295e-02,  5.7066e-02,
        -3.8011e-02,  1.2838e-02,  1.3942e-02, -4.0790e-02,  3.7204e-03,
        -4.1625e-02,  2.4442e-02, -3.6118e-02,  3.0810e-03,  9.4323e-03,
        -6.0105e-03, -3.7593e-02, -2.6934e-03,  3.3262e-02,  3.9216e-02,
        -4.0876e-03, -4.5825e-02, -1.1978e-02,  4.7572e-03,  1.5974e-06,
        -6.5151e-03, -1.9491e-02,  2.5499e-02,  1.9209e-02,  2.3816e-03,
        -4.3878e-02, -9.9081e-03,  1.8526e-02,  6.7799e-03,  3.0337e-03,
        -1.6067e-02,  3.2582e-02,  1.5914e-02,  2.3294e-03,  5.0949e-02,
         2.1208e-03,  3.9249e-03, -1.5111e-02, -1.0337e-02, -7.4579e-02,
         2.1548e-02,  1.4020e-02, -3.7949e-02, -1.1861e-01,  2.0228e-02,
        -1.1543e-02, -3.0923e-02, -2.4485e-02,  9.0431e-03,  2.9116e-02,
         2.4770e-02, -7.3306e-02,  9.4215e-02,  1.0

In [ ]:
import torch.nn.functional as F
cosine_similarity_scores = F.cosine_similarity(e1, e2, dim=0)

In [ ]:
cosine_similarity_scores

# Encoding is very good

tensor(0.0984, device='cuda:0')

In [ ]:
embeddings = sbert.encode(texts, convert_to_tensor=True)

Batches:   0%|          | 0/1357 [00:00<?, ?it/s]

In [ ]:
import torch.nn.functional as F
embeddings = F.normalize(embeddings, p=2, dim=1)
# normalize embeeding

In [ ]:
def multi_hot_encode(label_indices, num_classes):
    target = torch.zeros(num_classes)
    target[label_indices] = 1.0
    return target

In [ ]:
labels = torch.stack([multi_hot_encode(l, NUM_LABELS) for l in train_data["labels"]])

In [ ]:
labels[107]

tensor([0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
embeddings.shape

torch.Size([43410, 768])

In [ ]:
train_dataset = TensorDataset(embeddings.cpu(), labels)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

In [ ]:
#prepare test loader
test_data = dataset["test"]
texts = test_data["text"]
embeddings = sbert.encode(texts, convert_to_tensor=True, show_progress_bar=True)
embeddings = F.normalize(embeddings, p=2, dim=1)
labels = torch.stack([multi_hot_encode(l, NUM_LABELS) for l in test_data["labels"]])
test_dataset = TensorDataset(embeddings.cpu(), labels)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=True)

Batches:   0%|          | 0/170 [00:00<?, ?it/s]

In [ ]:
import torch.nn as nn


class NeuralNetwork(nn.Module):

  def __init__(self):

    super(NeuralNetwork,self).__init__()
    self.layer1=nn.Linear(768,10000)
    self.layer2=nn.Linear(10000,5000)
    self.layer3=nn.Linear(5000,2000)
    self.layer4=nn.Linear(2000,1000)
    self.layer5=nn.Linear(1000,500)
    self.layer6 = nn.Linear(500,28)

  def forward(self,sentence_embeddings):

    out=torch.relu(self.layer1(sentence_embeddings))
    out=torch.relu(self.layer2(out))
    out=torch.relu(self.layer3(out))
    out=torch.relu(self.layer4(out))
    out = torch.relu(self.layer5(out))
    out=self.layer6(out)

    return out

In [ ]:
model = NeuralNetwork()

In [ ]:
for batch,label in train_loader:
  output = model(batch)
  print(output.shape)
  break
# this should return 1,28

torch.Size([50, 28])


In [ ]:
# Define the Loss function

loss = nn.BCEWithLogitsLoss()

In [ ]:
# Define the optimiser

optimiser = torch.optim.Adam(model.parameters(), lr=0.0001)

In [ ]:
model.to(DEVICE)

NeuralNetwork(
  (layer1): Linear(in_features=768, out_features=10000, bias=True)
  (layer2): Linear(in_features=10000, out_features=5000, bias=True)
  (layer3): Linear(in_features=5000, out_features=2000, bias=True)
  (layer4): Linear(in_features=2000, out_features=1000, bias=True)
  (layer5): Linear(in_features=1000, out_features=500, bias=True)
  (layer6): Linear(in_features=500, out_features=28, bias=True)
)

In [ ]:
epochs = 10

for epoch in range(epochs):
    current_loss = 0
    num_batches = 0
    for batch,label in train_loader:
        num_batches += 1
        batch = batch.to(DEVICE)
        label = label.to(DEVICE)
        output = model(batch)
        loss_value = loss(output, label)
        current_loss += loss_value
        loss_value.backward()
        optimiser.step()

    print(f"epoch {epoch} loss : {current_loss/num_batches}")


epoch 0 loss : 0.2527000308036804
epoch 1 loss : 0.1555611491203308
epoch 2 loss : 0.14476630091667175
epoch 3 loss : 0.14204058051109314
epoch 4 loss : 0.16680490970611572
epoch 5 loss : 0.1413295716047287
epoch 6 loss : 0.15068376064300537
epoch 7 loss : 0.16220514476299286
epoch 8 loss : 0.1520695984363556
epoch 9 loss : 0.17052091658115387


In [ ]:
sentence = "i am very happy today"
embedding = sbert.encode(sentence, convert_to_tensor=True)
embedding = F.normalize(embedding, p=2, dim=0)
model(embedding)

tensor([-0.6448, -2.4620, -3.9029, -3.8088, -2.2524, -3.1648, -3.7971, -3.2620,
        -3.1906, -3.9464, -3.9935, -4.0983, -4.1216, -2.8841, -4.0309, -1.8819,
        -4.3284, -1.9989, -1.5267, -4.2635, -2.3495, -4.3261, -3.8990, -4.3711,
        -3.9115, -3.5224, -3.5703, -2.1931], device='cuda:0',
       grad_fn=<ViewBackward0>)

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score

all_preds, all_labels = [], []

with torch.no_grad():
    for data, labels in train_loader:
        data, labels = data.to(DEVICE), labels.to(DEVICE)
        outputs = model(data);
        all_preds.append(torch.sigmoid(outputs).cpu())
        all_labels.append(labels.cpu())

In [ ]:
from sklearn.metrics import f1_score
import numpy as np

preds = torch.cat(all_preds).numpy()
labels = torch.cat(all_labels).numpy()
optimal_thresholds = np.zeros(28)

# Removed values_to_test as we use all thresholds from roc_curve

for c in range(28):
    try:
        class_labels = labels[:, c]
        class_preds = preds[:, c]

        # Calculate ROC curve data points: FPR, TPR, and all thresholds
        fpr, tpr, thresholds = roc_curve(class_labels, class_preds)

        # Calculate Youden's J Statistic: J = TPR - FPR
        J = tpr - fpr

        # Find the threshold that maximizes J
        best_threshold = thresholds[np.argmax(J)]

        # Store and report AUROC (Area Under ROC Curve)
        optimal_thresholds[c] = best_threshold
        auc = roc_auc_score(class_labels, class_preds)
        print(f"Class {c}: Threshold={best_threshold:.3f}, Max J={np.max(J):.4f}, AUROC={auc:.4f}")

    except ValueError:
        optimal_thresholds[c] = 0.5 # Default if class is uniform (roc_curve raises ValueError)
        print(f"Class {c}: Uniform class, default Threshold=0.5")

print(f"\nOptimal thresholds array found: {optimal_thresholds}")

Class 0: Threshold=0.065, Max J=0.4702, AUROC=0.7310
Class 1: Threshold=0.019, Max J=0.1624, AUROC=0.5768
Class 2: Threshold=0.052, Max J=0.2785, AUROC=0.6379
Class 3: Threshold=0.088, Max J=0.2647, AUROC=0.6379
Class 4: Threshold=0.046, Max J=0.0238, AUROC=0.5101
Class 5: Threshold=0.007, Max J=0.1480, AUROC=0.5659
Class 6: Threshold=0.055, Max J=0.2014, AUROC=0.5995
Class 7: Threshold=0.057, Max J=0.1709, AUROC=0.5792
Class 8: Threshold=0.014, Max J=0.2514, AUROC=0.6059
Class 9: Threshold=0.019, Max J=0.1496, AUROC=0.5773
Class 10: Threshold=0.079, Max J=0.2558, AUROC=0.6226
Class 11: Threshold=0.051, Max J=0.2423, AUROC=0.6251
Class 12: Threshold=0.006, Max J=0.0396, AUROC=0.4676
Class 13: Threshold=0.012, Max J=0.3624, AUROC=0.6792
Class 14: Threshold=0.008, Max J=0.0413, AUROC=0.4685
Class 15: Threshold=0.049, Max J=0.6506, AUROC=0.8501
Class 16: Threshold=0.009, Max J=0.1245, AUROC=0.5683
Class 17: Threshold=0.009, Max J=0.4509, AUROC=0.7359
Class 18: Threshold=0.012, Max J=0.526

In [ ]:
def predict(sentence):
  prediction = torch.zeros(NUM_LABELS)
  embedding = sbert.encode(sentence, convert_to_tensor=True)
  # If embedding is a 1D tensor (single sentence), unsqueeze to make it 2D (batch_size=1)
  if embedding.dim() == 1:
    embedding = embedding.unsqueeze(0)
  embedding = F.normalize(embedding, p=2, dim=1) # Normalize along dimension 1 (features)
  output = model(embedding.to(DEVICE)) # Ensure input is on the correct device
  output = torch.sigmoid(output)
  for i in range(NUM_LABELS):
    # Access the output of the first (and only) item in the batch. output[0] is now a 1D tensor of probabilities.
    if output[0][i].item() > optimal_thresholds[i]:
      prediction[i] = 1
  return prediction

In [ ]:
train_data[10]

{'text': 'Demographics? I don’t know anybody under 35 who has cable tv.',
 'labels': [6],
 'id': 'eel6g5h'}

In [ ]:
labels[6]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
predict("Demographics? I don’t know anybody under 35 who has cable tv.")

tensor([0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 1., 1., 1.])

In [ ]:
ans = None
for batch,_ in test_loader:
  batch = batch.to(DEVICE)
  ans =model(batch)
  break

In [ ]:
ans[0]

tensor([-2.7723, -3.9266, -2.9122, -2.3341, -3.0423, -4.8985, -2.8446, -2.8035,
        -4.2433, -3.4100, -2.4530, -2.9338, -4.8871, -4.3729, -4.8373, -5.0157,
        -6.6319, -4.7457, -5.1047, -5.9986, -4.1497, -6.6476, -3.9204, -6.2820,
        -5.5965, -4.2100, -4.3938,  0.0424], device='cuda:0',
       grad_fn=<SelectBackward0>)